env:
  global:
    - CC_TEST_REPORTER_ID=d2724a227defec0d4fe91f5ecde77e684c0d9f468de5babf9aef61e1a5d1956f
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log
sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run grunt
addons:
  code_climate:
    repo_token: <token>
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info