sudo: required
dist: trusty
language: node_js
node_js:
  - "9"
install:
  - npm install
before_script:
  - npm install -g codecov
script:
  - npm test
  - npm run build
  - codecov
after_script:
  - bash <(curl -s https://codecov.io/bash) -t ${codecovTag}